{"name": "Получение заказов без авторизации", "status": "passed", "description": "Тест проверяет, что при получении заказов без авторизации возвращается ошибка 401", "start": 1729422905121, "stop": 1729422905362, "uuid": "fa2f0ec3-be86-4c1b-93ee-c2ffb96f7623", "historyId": "a6d50b3f12a3dee68529eafc90b3e719", "testCaseId": "a6d50b3f12a3dee68529eafc90b3e719", "fullName": "tests.test_get_orders.TestReceivingOrders#test_receiving_orders_without_authorization", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_orders"}, {"name": "subSuite", "value": "TestReceivingOrders"}, {"name": "host", "value": "NikashaXD"}, {"name": "thread", "value": "7516-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_orders"}]}